// Icon — Lucide React adapter. Boilerplate uses an inline hand-tuned SVG
// set; we replace it with lucide-react (same iconography, larger catalog,
// better tree-shaking) while matching the boilerplate's 1.7 stroke width
// and 14px sizing. Access as Icon.X.
//
// Icon —— Lucide React 适配。boilerplate 用内联手调 SVG；替换为 lucide-react
// （同款设计语言、更大目录、tree-shaking 友好），匹配 1.7 描边 + 14px 尺寸。
// 访问形如 Icon.X。

import {
  Search, Plus, ChevronRight, ChevronDown, ChevronUp, X, Check, Bell, Command,
  Settings, MessageSquare, Hammer, Play, Library, User, Bot, Brain, Wrench,
  Code, Paperclip, File, FileText, Image, Send, Square, Sparkles, AtSign,
  Mic, AlertCircle, CheckCircle, Clock, Folder, Database, Globe, Workflow,
  GitBranch, Cpu, Zap, Layers, KeyRound, Brush, Eye, EyeOff, Copy, Trash,
  RefreshCw, StopCircle, ArrowUp, ArrowRight, CornerDownLeft, Pin, Filter,
  MoreHorizontal, Menu, Inbox, Terminal, HelpCircle, Pause, Activity, Server,
  Box, Boxes, Package, ListChecks, Edit, Sun, Moon, Archive,
} from "lucide-react";

const wrap = (Comp) => (props) => (
  <Comp size={14} strokeWidth={1.7} className="icon" {...props} />
);

export const Icon = {
  Search: wrap(Search),
  Plus: wrap(Plus),
  ChevronRight: wrap(ChevronRight),
  ChevronDown: wrap(ChevronDown),
  ChevronUp: wrap(ChevronUp),
  X: wrap(X),
  Check: wrap(Check),
  Bell: wrap(Bell),
  Command: wrap(Command),
  Settings: wrap(Settings),
  MessageSquare: wrap(MessageSquare),
  Hammer: wrap(Hammer),
  Play: wrap(Play),
  Library: wrap(Library),
  User: wrap(User),
  Bot: wrap(Bot),
  Brain: wrap(Brain),
  Wrench: wrap(Wrench),
  Code: wrap(Code),
  Paperclip: wrap(Paperclip),
  File: wrap(File),
  FileText: wrap(FileText),
  Image: wrap(Image),
  Send: wrap(Send),
  Square: wrap(Square),
  Sparkles: wrap(Sparkles),
  At: wrap(AtSign),
  Mic: wrap(Mic),
  AlertCircle: wrap(AlertCircle),
  CheckCircle: wrap(CheckCircle),
  Clock: wrap(Clock),
  Folder: wrap(Folder),
  Database: wrap(Database),
  Globe: wrap(Globe),
  Workflow: wrap(Workflow),
  GitBranch: wrap(GitBranch),
  Cpu: wrap(Cpu),
  Zap: wrap(Zap),
  Layers: wrap(Layers),
  KeyRound: wrap(KeyRound),
  Brush: wrap(Brush),
  Eye: wrap(Eye),
  EyeOff: wrap(EyeOff),
  Copy: wrap(Copy),
  Trash: wrap(Trash),
  Refresh: wrap(RefreshCw),
  StopCircle: wrap(StopCircle),
  ArrowUp: wrap(ArrowUp),
  ArrowRight: wrap(ArrowRight),
  CornerDownLeft: wrap(CornerDownLeft),
  Pin: wrap(Pin),
  Filter: wrap(Filter),
  MoreHorizontal: wrap(MoreHorizontal),
  Menu: wrap(Menu),
  Inbox: wrap(Inbox),
  Terminal: wrap(Terminal),
  HelpCircle: wrap(HelpCircle),
  Pause: wrap(Pause),
  Activity: wrap(Activity),
  Server: wrap(Server),
  Box: wrap(Box),
  Boxes: wrap(Boxes),
  Package: wrap(Package),
  ListChecks: wrap(ListChecks),
  Edit: wrap(Edit),
  Sun: wrap(Sun),
  Moon: wrap(Moon),
  Archive: wrap(Archive),
};
