// GREETINGS — 380-entry rotating pool for the welcome page.
// Tag taxonomy:
//   A confident "Your X"   B forge/anvil theme   C build/ship/make
//   D what/where/how       E continuation        F short imperatives
//   G time-aware (G-morning / G-night sub-buckets)
//   H high-stakes drama    I deadpan/witty       J soft/patient
//   K AI self-reference    L aphorisms           M name-bearing ({name})
//   N self-mentioning Forgify   O misc
//
// GREETINGS —— 380 条欢迎页问候语池,15 大类。含 {name} 的句子在
// useGreeting 里按 displayName 是否可用过滤。

export const GREETINGS = [
  // A — Your move family (25)
  { text: "Your move, {name}.", tags: ["A","M"] },
  { text: "Your call, {name}.", tags: ["A","M"] },
  { text: "Your turn.", tags: ["A"] },
  { text: "Your shot.", tags: ["A"] },
  { text: "Your serve.", tags: ["A"] },
  { text: "Your play.", tags: ["A"] },
  { text: "Your move.", tags: ["A"] },
  { text: "The mic's yours.", tags: ["A"] },
  { text: "The floor is yours.", tags: ["A"] },
  { text: "Take the floor.", tags: ["A"] },
  { text: "Take the wheel.", tags: ["A"] },
  { text: "Take the lead.", tags: ["A"] },
  { text: "Take it from here.", tags: ["A"] },
  { text: "Lead the way.", tags: ["A"] },
  { text: "Set the pace.", tags: ["A"] },
  { text: "Set the table.", tags: ["A"] },
  { text: "Call it.", tags: ["A"] },
  { text: "Make the call.", tags: ["A"] },
  { text: "You drive.", tags: ["A"] },
  { text: "Steer the ship.", tags: ["A"] },
  { text: "It's all you.", tags: ["A"] },
  { text: "Over to you.", tags: ["A"] },
  { text: "You first.", tags: ["A"] },
  { text: "All yours.", tags: ["A"] },
  { text: "The day's yours, {name}.", tags: ["A","M"] },

  // B — Forge/anvil theme (45)
  { text: "The forge is hot.", tags: ["B"] },
  { text: "The forge is breathing.", tags: ["B"] },
  { text: "The forge is awake.", tags: ["B"] },
  { text: "The forge is yours.", tags: ["B"] },
  { text: "The anvil's waiting.", tags: ["B"] },
  { text: "The anvil's ringing.", tags: ["B"] },
  { text: "The iron is ready.", tags: ["B"] },
  { text: "The iron is hot.", tags: ["B"] },
  { text: "The fire's lit.", tags: ["B"] },
  { text: "The fire's high.", tags: ["B"] },
  { text: "The kiln is loud.", tags: ["B"] },
  { text: "The kiln is warming up.", tags: ["B"] },
  { text: "The bellows are ready.", tags: ["B"] },
  { text: "The coal's burning, {name}.", tags: ["B","M"] },
  { text: "The smithy's open.", tags: ["B"] },
  { text: "The shop is open, {name}.", tags: ["B","M"] },
  { text: "The flame's steady.", tags: ["B"] },
  { text: "Strike while it's hot.", tags: ["B"] },
  { text: "Strike clean.", tags: ["B"] },
  { text: "Hammer's in your hand.", tags: ["B"] },
  { text: "Hammer down.", tags: ["B"] },
  { text: "Sparks fly when you say so.", tags: ["B"] },
  { text: "Spark something.", tags: ["B"] },
  { text: "Lay it on the anvil.", tags: ["B"] },
  { text: "Lay the iron down.", tags: ["B"] },
  { text: "Hot iron, sharp mind.", tags: ["B"] },
  { text: "Quench it later.", tags: ["B"] },
  { text: "Tempered and ready.", tags: ["B"] },
  { text: "Steel sharpens steel.", tags: ["B"] },
  { text: "Iron doesn't shape itself.", tags: ["B"] },
  { text: "Heat. Strike. Repeat.", tags: ["B"] },
  { text: "Stoke the fire.", tags: ["B"] },
  { text: "Light the forge.", tags: ["B"] },
  { text: "Forge mode: on.", tags: ["B"] },
  { text: "Sharpen something today.", tags: ["B"] },
  { text: "On the anvil today.", tags: ["B"] },
  { text: "What's burning?", tags: ["B","D"] },
  { text: "What's on the anvil?", tags: ["B","D"] },
  { text: "What needs forging?", tags: ["B","D"] },
  { text: "What are we forging today?", tags: ["B","D"] },
  { text: "What are we hammering today?", tags: ["B","D"] },
  { text: "From iron to instrument.", tags: ["B"] },
  { text: "From cold to forged.", tags: ["B"] },
  { text: "From kindling to flame.", tags: ["B"] },
  { text: "From spark to ship.", tags: ["B"] },

  // C — Build/Ship/Make (40)
  { text: "Let's build something.", tags: ["C"] },
  { text: "Let's make something.", tags: ["C"] },
  { text: "Let's ship something.", tags: ["C"] },
  { text: "Let's get into it.", tags: ["C"] },
  { text: "Let's get to work.", tags: ["C"] },
  { text: "Let's roll.", tags: ["C"] },
  { text: "Let's go.", tags: ["C"] },
  { text: "Let's see what you've got.", tags: ["C"] },
  { text: "Build something real.", tags: ["C"] },
  { text: "Build it small. Ship it fast.", tags: ["C"] },
  { text: "Make something.", tags: ["C"] },
  { text: "Make it count.", tags: ["C"] },
  { text: "Make it sharp.", tags: ["C"] },
  { text: "Make it true, then make it fast.", tags: ["C"] },
  { text: "Ship something good.", tags: ["C"] },
  { text: "Ready to ship.", tags: ["C"] },
  { text: "Time to make something.", tags: ["C"] },
  { text: "Today we build.", tags: ["C"] },
  { text: "Today we forge.", tags: ["C","B"] },
  { text: "Today we ship.", tags: ["C"] },
  { text: "Today we move.", tags: ["C"] },
  { text: "Today we cut deep.", tags: ["C"] },
  { text: "Today we hit clean.", tags: ["C"] },
  { text: "Today we land the change.", tags: ["C"] },
  { text: "Today we end the open loops.", tags: ["C"] },
  { text: "Today we close the tab.", tags: ["C"] },
  { text: "From zero to draft.", tags: ["C"] },
  { text: "From draft to ship.", tags: ["C"] },
  { text: "From idea to artifact.", tags: ["C"] },
  { text: "From rough to finished.", tags: ["C"] },
  { text: "From scratch to scale.", tags: ["C"] },
  { text: "Build first. Polish later.", tags: ["C"] },
  { text: "Forge first. Doubt later.", tags: ["C","B"] },
  { text: "Sketch or ship today?", tags: ["C","D"] },
  { text: "Build or break today?", tags: ["C","D"] },
  { text: "Idea or execution today?", tags: ["C","D"] },
  { text: "Push or polish today?", tags: ["C","D"] },
  { text: "Forge or fix today?", tags: ["C","D","B"] },
  { text: "Plan or pounce today?", tags: ["C","D"] },
  { text: "Notes or code today?", tags: ["C","D"] },

  // D — What/Where/How (30)
  { text: "What's first?", tags: ["D"] },
  { text: "What's next?", tags: ["D"] },
  { text: "What's hot?", tags: ["D"] },
  { text: "What's cooking?", tags: ["D"] },
  { text: "What's brewing?", tags: ["D"] },
  { text: "What's the plan?", tags: ["D"] },
  { text: "What's the play?", tags: ["D"] },
  { text: "What's the move?", tags: ["D"] },
  { text: "What are we building today?", tags: ["D","C"] },
  { text: "What are we shipping today?", tags: ["D","C"] },
  { text: "What are we wiring today?", tags: ["D"] },
  { text: "What's burning brightest?", tags: ["D","B"] },
  { text: "Where to today?", tags: ["D"] },
  { text: "Where are we headed?", tags: ["D"] },
  { text: "Where are we taking this?", tags: ["D"] },
  { text: "Where do we start?", tags: ["D"] },
  { text: "How can I help?", tags: ["D","K"] },
  { text: "How big are we thinking?", tags: ["D"] },
  { text: "How bold are we feeling?", tags: ["D"] },
  { text: "How fast can we ship?", tags: ["D","C"] },
  { text: "Why not now?", tags: ["D"] },
  { text: "Easy or hard today?", tags: ["D"] },
  { text: "Big or small today?", tags: ["D"] },
  { text: "New or unfinished today?", tags: ["D"] },
  { text: "Long day or short sprint?", tags: ["D"] },
  { text: "Got a flow to wire?", tags: ["D"] },
  { text: "Got a function to forge?", tags: ["D","B"] },
  { text: "Got a handler to ship?", tags: ["D","C"] },
  { text: "Got a workflow to test?", tags: ["D"] },
  { text: "Got a bug to corner?", tags: ["D"] },

  // E — Continuation (15)
  { text: "Pick up where you left off.", tags: ["E"] },
  { text: "Pick up the thread.", tags: ["E"] },
  { text: "Right where you left off.", tags: ["E"] },
  { text: "Resume the chase.", tags: ["E"] },
  { text: "Back at it.", tags: ["E"] },
  { text: "Back in.", tags: ["E"] },
  { text: "Back to it.", tags: ["E"] },
  { text: "Back to forging.", tags: ["E","B"] },
  { text: "Welcome back, {name}.", tags: ["E","M"] },
  { text: "Where were we?", tags: ["E"] },
  { text: "Keep going.", tags: ["E"] },
  { text: "Continue the build.", tags: ["E","C"] },
  { text: "Don't break stride.", tags: ["E"] },
  { text: "Pick up the iron.", tags: ["E","B"] },
  { text: "Open thread, hot forge.", tags: ["E","B"] },

  // F — Short imperatives (30)
  { text: "Begin.", tags: ["F"] },
  { text: "Speak.", tags: ["F"] },
  { text: "Strike.", tags: ["F","B"] },
  { text: "Build.", tags: ["F","C"] },
  { text: "Ship.", tags: ["F","C"] },
  { text: "Forge.", tags: ["F","B"] },
  { text: "Make.", tags: ["F","C"] },
  { text: "Move.", tags: ["F"] },
  { text: "Go.", tags: ["F"] },
  { text: "Start.", tags: ["F"] },
  { text: "Now.", tags: ["F"] },
  { text: "Today.", tags: ["F"] },
  { text: "Whenever.", tags: ["F"] },
  { text: "Hit it.", tags: ["F"] },
  { text: "Send it.", tags: ["F"] },
  { text: "Press send.", tags: ["F"] },
  { text: "Sound off.", tags: ["F"] },
  { text: "Light it up.", tags: ["F"] },
  { text: "Open the floor, {name}.", tags: ["F","M"] },
  { text: "Roll the dice.", tags: ["F"] },
  { text: "Game on.", tags: ["F"] },
  { text: "Lay it on me.", tags: ["F","K"] },
  { text: "Just say the word.", tags: ["F"] },
  { text: "Ready when you are.", tags: ["F","K"] },
  { text: "Just start.", tags: ["F"] },
  { text: "Just begin.", tags: ["F"] },
  { text: "Start anywhere.", tags: ["F"] },
  { text: "Start sloppy.", tags: ["F"] },
  { text: "Start before doubt.", tags: ["F"] },
  { text: "Start before perfect.", tags: ["F"] },

  // G — Time-aware (20). 13 morning / 7 night
  { text: "Morning, {name}.", tags: ["G","G-morning","M"] },
  { text: "Good morning. What's first?", tags: ["G","G-morning"] },
  { text: "Coffee's down. Ideas up?", tags: ["G","G-morning"] },
  { text: "First light. First move.", tags: ["G","G-morning"] },
  { text: "Fresh start.", tags: ["G","G-morning"] },
  { text: "Day's young. So are we.", tags: ["G","G-morning"] },
  { text: "Caffeine acquired?", tags: ["G","G-morning"] },
  { text: "Post-lunch sharpening.", tags: ["G"] },
  { text: "Afternoon stretch — and ship.", tags: ["G","C"] },
  { text: "Sun's high. Forge higher.", tags: ["G","B"] },
  { text: "Working late, {name}.", tags: ["G","G-night","M"] },
  { text: "Burning the midnight oil.", tags: ["G","G-night"] },
  { text: "Still here? Let's go.", tags: ["G","G-night"] },
  { text: "Late shift's the best shift.", tags: ["G","G-night"] },
  { text: "Quiet hours. Loud ideas.", tags: ["G","G-night"] },
  { text: "After-hours forge.", tags: ["G","G-night","B"] },
  { text: "Night forge.", tags: ["G","G-night","B"] },
  { text: "Weekend forge.", tags: ["G","B"] },
  { text: "Saturday build.", tags: ["G","C"] },
  { text: "Sunday strikes hit different.", tags: ["G"] },

  // H — High-stakes drama (20)
  { text: "The clock's running.", tags: ["H"] },
  { text: "Big day, {name}.", tags: ["H","M"] },
  { text: "Stage is set.", tags: ["H"] },
  { text: "Lights are on.", tags: ["H"] },
  { text: "Crowd's quiet.", tags: ["H"] },
  { text: "Curtain's up.", tags: ["H"] },
  { text: "Make it matter.", tags: ["H"] },
  { text: "No half-measures.", tags: ["H"] },
  { text: "Go big.", tags: ["H"] },
  { text: "Burn it bright.", tags: ["H"] },
  { text: "Don't blink.", tags: ["H"] },
  { text: "Eyes forward.", tags: ["H"] },
  { text: "Bring your A game.", tags: ["H"] },
  { text: "This one counts.", tags: ["H"] },
  { text: "Set the bar.", tags: ["H"] },
  { text: "Raise the bar.", tags: ["H"] },
  { text: "Reset the bar.", tags: ["H"] },
  { text: "Pull no punches.", tags: ["H"] },
  { text: "Don't be polite about it.", tags: ["H"] },
  { text: "Aim for finished.", tags: ["H","C"] },

  // I — Deadpan / Witty (25)
  { text: "Don't keep me waiting.", tags: ["I"] },
  { text: "I cleared my schedule.", tags: ["I","K"] },
  { text: "The fire's been hot for an hour.", tags: ["I","B"] },
  { text: "Surprise me.", tags: ["I","K"] },
  { text: "Impress yourself.", tags: ["I"] },
  { text: "Hope you brought ideas.", tags: ["I"] },
  { text: "The good ones come early.", tags: ["I"] },
  { text: "Best to start before second-guessing.", tags: ["I"] },
  { text: "Try not to ship a bug.", tags: ["I"] },
  { text: "Try not to break prod.", tags: ["I"] },
  { text: "Try not to make it weird.", tags: ["I"] },
  { text: "Today, we earn the lunch break.", tags: ["I"] },
  { text: "I'm not above flattery. Just start.", tags: ["I","K"] },
  { text: "Surprise the anvil.", tags: ["I","B"] },
  { text: "Bad ideas welcome — fire fixes them.", tags: ["I"] },
  { text: "Half-baked is half-cooked is half-done.", tags: ["I"] },
  { text: "Even bad ideas spark fire.", tags: ["I"] },
  { text: "Especially the half-baked ones.", tags: ["I"] },
  { text: "Doodles welcome (in text).", tags: ["I"] },
  { text: "Word-vomit it. Then we polish.", tags: ["I"] },
  { text: "The polish comes free.", tags: ["I"] },
  { text: "Type fast. Edit later.", tags: ["I"] },
  { text: "Stream of consciousness welcome.", tags: ["I"] },
  { text: "Half-finished is fine. Get to half.", tags: ["I"] },
  { text: "Even one sentence is a start.", tags: ["I"] },

  // J — Soft / Patient (20)
  { text: "Take your time, {name}.", tags: ["J","M"] },
  { text: "Tell me everything.", tags: ["J","K"] },
  { text: "Show me what you've got.", tags: ["J"] },
  { text: "No rush. But also — go.", tags: ["J"] },
  { text: "I'll wait. But not for long.", tags: ["J","K"] },
  { text: "Whenever you're ready.", tags: ["J"] },
  { text: "Whatever you've got.", tags: ["J"] },
  { text: "Wherever this leads.", tags: ["J"] },
  { text: "Whatever feels right.", tags: ["J"] },
  { text: "However you want to.", tags: ["J"] },
  { text: "As big or as small as you want.", tags: ["J"] },
  { text: "Bring me anything.", tags: ["J","K"] },
  { text: "Bring me a problem.", tags: ["J","K"] },
  { text: "Bring me a brief.", tags: ["J","K"] },
  { text: "Bring me a question.", tags: ["J","K"] },
  { text: "Bring me an idea worth forging.", tags: ["J","K","B"] },
  { text: "Drop something in.", tags: ["J"] },
  { text: "Drop the brief.", tags: ["J"] },
  { text: "Drop the seed.", tags: ["J"] },
  { text: "Plant the question.", tags: ["J"] },

  // K — AI self-reference (20)
  { text: "I'm all ears, {name}.", tags: ["K","M"] },
  { text: "I'm ready when you are.", tags: ["K"] },
  { text: "Standing by.", tags: ["K"] },
  { text: "Locked in.", tags: ["K"] },
  { text: "Tuned in.", tags: ["K"] },
  { text: "Cued up.", tags: ["K"] },
  { text: "On your mark.", tags: ["K"] },
  { text: "Hand on the bellows.", tags: ["K","B"] },
  { text: "Pen up, page open.", tags: ["K"] },
  { text: "Sharpened up.", tags: ["K","B"] },
  { text: "Whenever you say.", tags: ["K"] },
  { text: "Hand me the spark.", tags: ["K","B"] },
  { text: "Hand me the brief.", tags: ["K"] },
  { text: "Hand me the puzzle.", tags: ["K"] },
  { text: "Throw me a curveball.", tags: ["K"] },
  { text: "Pass me the iron.", tags: ["K","B"] },
  { text: "Pass me the design.", tags: ["K"] },
  { text: "Tell me the shape of it.", tags: ["K"] },
  { text: "Show me the rough draft.", tags: ["K"] },
  { text: "Bring the chaos. I'll bring order.", tags: ["K"] },

  // L — Aphorisms (15)
  { text: "Slow is smooth, smooth is fast.", tags: ["L"] },
  { text: "Done is the polish.", tags: ["L"] },
  { text: "The hard part is starting.", tags: ["L"] },
  { text: "The next move is always the move.", tags: ["L"] },
  { text: "Begin badly, refine ruthlessly.", tags: ["L"] },
  { text: "Discipline beats inspiration.", tags: ["L"] },
  { text: "Make small bets. Win often.", tags: ["L"] },
  { text: "Compounding is silent.", tags: ["L"] },
  { text: "Friction first, fluency after.", tags: ["L"] },
  { text: "Pace beats sprint.", tags: ["L"] },
  { text: "Confidence first, edits later.", tags: ["L"] },
  { text: "Aim higher.", tags: ["L"] },
  { text: "Stillness, then strike.", tags: ["L","B"] },
  { text: "Hush. Then hammer.", tags: ["L","B"] },
  { text: "Quiet hands, sharp ideas.", tags: ["L"] },

  // M — Personalized with Weilin/{name} (15)
  { text: "Game face, {name}.", tags: ["M"] },
  { text: "Steady hand, {name}.", tags: ["M"] },
  { text: "Sharp eye, {name}.", tags: ["M"] },
  { text: "Light hands, {name}.", tags: ["M"] },
  { text: "Tight loop, {name}.", tags: ["M"] },
  { text: "Right tool, {name}.", tags: ["M"] },
  { text: "Big idea, {name}?", tags: ["M"] },
  { text: "Easy mode or hard mode, {name}?", tags: ["M"] },
  { text: "Place your bets, {name}.", tags: ["M"] },
  { text: "Start anyway, {name}.", tags: ["M","F"] },
  { text: "Forgify is yours, {name}.", tags: ["M","N"] },
  { text: "Hand on the hammer, {name}.", tags: ["M","B"] },
  { text: "Eyes on the iron, {name}.", tags: ["M","B"] },
  { text: "Sound off, {name}.", tags: ["M","F"] },
  { text: "The smithy is open, {name}.", tags: ["M","B"] },

  // N — Forgify self-mention (10)
  { text: "Forgify, lights on.", tags: ["N"] },
  { text: "Forgify is up.", tags: ["N"] },
  { text: "Forgify is hot.", tags: ["N","B"] },
  { text: "Forgify is open.", tags: ["N"] },
  { text: "Forgify, ready.", tags: ["N"] },
  { text: "Forgify, listening.", tags: ["N","K"] },
  { text: "Forgify says: speak.", tags: ["N","K"] },
  { text: "The smithy is named Forgify.", tags: ["N","B"] },
  { text: "Forgify is online.", tags: ["N"] },
  { text: "Forgify is warmed up.", tags: ["N","B"] },

  // O — Misc (50)
  { text: "Plot something.", tags: ["O"] },
  { text: "Pull a rabbit from the kiln.", tags: ["O","B"] },
  { text: "The blueprint's in your head — let it out.", tags: ["O"] },
  { text: "Let it leak.", tags: ["O"] },
  { text: "Let it spill.", tags: ["O"] },
  { text: "Let it flow.", tags: ["O"] },
  { text: "Speak it into the editor.", tags: ["O"] },
  { text: "Whisper it. I'll hear.", tags: ["O","K"] },
  { text: "One sentence. Then we go.", tags: ["O"] },
  { text: "One line. Then I'll guess the rest.", tags: ["O","K"] },
  { text: "Outlines welcome.", tags: ["O"] },
  { text: "Drafts welcome.", tags: ["O"] },
  { text: "The shop is quiet — fill it.", tags: ["O","B"] },
  { text: "The pipeline's quiet — fill it.", tags: ["O"] },
  { text: "The runway is clean.", tags: ["O"] },
  { text: "The path is yours.", tags: ["O","A"] },
  { text: "The dock is clear — ship.", tags: ["O","C"] },
  { text: "Cursor in. Mind in.", tags: ["O"] },
  { text: "Slow hands, fast brain.", tags: ["O","L"] },
  { text: "Click of the keyboard, ring of the anvil.", tags: ["O","B"] },
  { text: "Plumbing today, or polish?", tags: ["O","D"] },
  { text: "A handler before lunch?", tags: ["O"] },
  { text: "A function before lunch?", tags: ["O"] },
  { text: "New flow, new fire.", tags: ["O","B"] },
  { text: "New function, new spark.", tags: ["O","B"] },
  { text: "The flow needs you.", tags: ["O"] },
  { text: "Functions on the anvil?", tags: ["O","B"] },
  { text: "Workflow on the anvil?", tags: ["O","B"] },
  { text: "Spelunking today?", tags: ["O","D"] },
  { text: "Hunting bugs today?", tags: ["O","D"] },
  { text: "Drafting today?", tags: ["O","D"] },
  { text: "Sketching today?", tags: ["O","D"] },
  { text: "Wiring today?", tags: ["O","D"] },
  { text: "Forging today?", tags: ["O","D","B"] },
  { text: "Hammering today?", tags: ["O","D","B"] },
  { text: "Shipping today?", tags: ["O","D","C"] },
  { text: "Building today?", tags: ["O","D","C"] },
  { text: "Show me audacity.", tags: ["O","H"] },
  { text: "Show me a finished thing.", tags: ["O","C"] },
  { text: "Show me power.", tags: ["O","H"] },
  { text: "Be loud, on the inside.", tags: ["O"] },
  { text: "Got a thread to follow?", tags: ["O","D"] },
  { text: "Got a mess to sort?", tags: ["O","D"] },
  { text: "Got a doc to draft?", tags: ["O","D"] },
  { text: "A flow before the standup?", tags: ["O"] },
  { text: "A function before tea?", tags: ["O"] },
  { text: "Brief, scope, ship.", tags: ["O","C"] },
  { text: "Brief me.", tags: ["O","K"] },
  { text: "Scope me.", tags: ["O"] },
  { text: "Surface area first, depth later.", tags: ["O","L"] },
];
