package handler

import (
	"fmt"
	"strings"

	handlerdomain "github.com/sunweilin/forgify/backend/internal/domain/handler"
)

// AssembleClass produces user_handler.py contents from a VersionDraft: a `HandlerImpl`
// class with __init__(self, ...initArgs), shutdown(self), and one def per method.
//
// AssembleClass 从 VersionDraft 生成 user_handler.py：一个 `HandlerImpl` 类，含
// __init__(self, ...initArgs)、shutdown(self)、每 method 一个 def。
func AssembleClass(d *VersionDraft) string {
	var b strings.Builder
	b.WriteString("# Auto-assembled by Forgify from ops; do not edit by hand.\n")
	if d.Imports != "" {
		b.WriteString(d.Imports)
		if !strings.HasSuffix(d.Imports, "\n") {
			b.WriteByte('\n')
		}
		b.WriteByte('\n')
	}
	b.WriteString("class HandlerImpl:\n")

	b.WriteString("    def __init__(self")
	for _, a := range d.InitArgsSchema {
		fmt.Fprintf(&b, ", %s: %s", a.Name, pythonType(a.Type))
		if !a.Required {
			fmt.Fprintf(&b, " = %s", pythonDefault(a.Default))
		}
	}
	b.WriteString("):\n")
	writeBody(&b, d.InitBody)
	b.WriteByte('\n')

	b.WriteString("    def shutdown(self):\n")
	writeBody(&b, d.ShutdownBody)
	b.WriteByte('\n')

	for _, m := range d.Methods {
		writeMethod(&b, m)
		b.WriteByte('\n')
	}
	return b.String()
}

func writeMethod(b *strings.Builder, m handlerdomain.MethodSpec) {
	fmt.Fprintf(b, "    def %s(self", m.Name)
	for _, a := range m.Inputs {
		fmt.Fprintf(b, ", %s: %s", a.Name, pythonType(a.Type))
	}
	b.WriteString("):\n")
	writeBody(b, m.Body)
}

func writeBody(b *strings.Builder, body string) {
	if strings.TrimSpace(body) == "" {
		b.WriteString("        pass\n")
		return
	}
	for _, line := range strings.Split(body, "\n") {
		if line == "" {
			b.WriteByte('\n')
			continue
		}
		b.WriteString("        ")
		b.WriteString(line)
		b.WriteByte('\n')
	}
}

func pythonType(t string) string {
	switch t {
	case "string":
		return "str"
	case "integer":
		return "int"
	case "number":
		return "float"
	case "boolean":
		return "bool"
	case "object":
		return "dict"
	case "array":
		return "list"
	default:
		return "object"
	}
}

func pythonDefault(v any) string {
	if v == nil {
		return "None"
	}
	switch x := v.(type) {
	case bool:
		if x {
			return "True"
		}
		return "False"
	case string:
		var sb strings.Builder
		sb.WriteByte('"')
		for _, r := range x {
			switch r {
			case '\\':
				sb.WriteString(`\\`)
			case '"':
				sb.WriteString(`\"`)
			case '\n':
				sb.WriteString(`\n`)
			case '\r':
				sb.WriteString(`\r`)
			case '\t':
				sb.WriteString(`\t`)
			default:
				sb.WriteRune(r)
			}
		}
		sb.WriteByte('"')
		return sb.String()
	default:
		return fmt.Sprintf("%v", x)
	}
}

// DriverScript is the constant Python driver serving the stdio line-JSON RPC protocol:
// init → ready, then a message loop (call → return/error, generator yields → progress,
// shutdown → runs shutdown()). Private methods (leading "_") are not callable.
//
// DriverScript 是常量 Python driver，承担 stdio 行-JSON RPC：init → ready，再消息循环
// （call → return/error，generator yield → progress，shutdown → 跑 shutdown()）。`_` 开头私有方法不可调。
const DriverScript = `# Auto-generated by Forgify; do not edit.
import sys, json, traceback
from user_handler import HandlerImpl


def respond(payload):
    sys.stdout.write(json.dumps(payload) + "\n")
    sys.stdout.flush()


def main():
    init_line = sys.stdin.readline()
    if not init_line:
        return
    init_msg = json.loads(init_line)
    try:
        handler = HandlerImpl(**(init_msg.get("args") or {}))
        respond({"type": "ready"})
    except Exception as e:
        respond({"type": "init_error", "error": str(e), "trace": traceback.format_exc()})
        return

    for line in sys.stdin:
        if not line.strip():
            continue
        msg = json.loads(line)
        msg_type = msg.get("type")
        if msg_type == "shutdown":
            try:
                handler.shutdown()
            except Exception:
                pass
            break
        if msg_type == "call":
            request_id = msg["id"]
            method_name = msg["method"]
            args = msg.get("args", {}) or {}
            if method_name.startswith("_"):
                respond({"type": "error", "id": request_id, "error": "private method: " + method_name, "trace": ""})
                continue
            try:
                method = getattr(handler, method_name)
            except AttributeError:
                respond({"type": "error", "id": request_id, "error": "no such method: " + method_name, "trace": ""})
                continue
            try:
                result = method(**args)
                if hasattr(result, "__iter__") and not isinstance(result, (str, bytes, list, dict)):
                    final = None
                    for item in result:
                        if isinstance(item, dict) and "progress" in item:
                            respond({"type": "progress", "id": request_id, "data": item["progress"]})
                        else:
                            final = item
                    respond({"type": "return", "id": request_id, "data": final})
                else:
                    respond({"type": "return", "id": request_id, "data": result})
            except Exception as e:
                respond({"type": "error", "id": request_id, "error": str(e), "trace": traceback.format_exc()})


if __name__ == "__main__":
    main()
`
